// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/scheduler.proto

package scheduler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_UNSPECIFIED                MessageType = 0
	MessageType_UPDATE_HOTEL               MessageType = 1
	MessageType_UPDATE_REVIEW              MessageType = 2
	MessageType_UPDATE_TRANSLATION         MessageType = 3
	MessageType_FETCH_MISSING_TRANSLATIONS MessageType = 4
	MessageType_FETCH_MISSING_REVIEWS      MessageType = 5
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UPDATE_HOTEL",
		2: "UPDATE_REVIEW",
		3: "UPDATE_TRANSLATION",
		4: "FETCH_MISSING_TRANSLATIONS",
		5: "FETCH_MISSING_REVIEWS",
	}
	MessageType_value = map[string]int32{
		"UNSPECIFIED":                0,
		"UPDATE_HOTEL":               1,
		"UPDATE_REVIEW":              2,
		"UPDATE_TRANSLATION":         3,
		"FETCH_MISSING_TRANSLATIONS": 4,
		"FETCH_MISSING_REVIEWS":      5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_scheduler_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_scheduler_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

type TriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	MessageType   MessageType            `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3,enum=scheduler.MessageType" json:"message_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRequest) Reset() {
	*x = TriggerRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRequest) ProtoMessage() {}

func (x *TriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRequest.ProtoReflect.Descriptor instead.
func (*TriggerRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *TriggerRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TriggerRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TriggerRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *TriggerRequest) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_UNSPECIFIED
}

type TriggerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	JobsQueued    int32                  `protobuf:"varint,4,opt,name=jobs_queued,json=jobsQueued,proto3" json:"jobs_queued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerResponse) Reset() {
	*x = TriggerResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerResponse) ProtoMessage() {}

func (x *TriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerResponse.ProtoReflect.Descriptor instead.
func (*TriggerResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TriggerResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TriggerResponse) GetJobsQueued() int32 {
	if x != nil {
		return x.JobsQueued
	}
	return 0
}

type ScheduleStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleStatusRequest) Reset() {
	*x = ScheduleStatusRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleStatusRequest) ProtoMessage() {}

func (x *ScheduleStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleStatusRequest.ProtoReflect.Descriptor instead.
func (*ScheduleStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *ScheduleStatusRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ScheduleStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	LastRun       int64                  `protobuf:"varint,3,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	NextRun       int64                  `protobuf:"varint,4,opt,name=next_run,json=nextRun,proto3" json:"next_run,omitempty"`
	ScheduleInfo  map[string]string      `protobuf:"bytes,5,rep,name=schedule_info,json=scheduleInfo,proto3" json:"schedule_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleStatusResponse) Reset() {
	*x = ScheduleStatusResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleStatusResponse) ProtoMessage() {}

func (x *ScheduleStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleStatusResponse.ProtoReflect.Descriptor instead.
func (*ScheduleStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *ScheduleStatusResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ScheduleStatusResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ScheduleStatusResponse) GetLastRun() int64 {
	if x != nil {
		return x.LastRun
	}
	return 0
}

func (x *ScheduleStatusResponse) GetNextRun() int64 {
	if x != nil {
		return x.NextRun
	}
	return 0
}

func (x *ScheduleStatusResponse) GetScheduleInfo() map[string]string {
	if x != nil {
		return x.ScheduleInfo
	}
	return nil
}

var File_proto_scheduler_proto protoreflect.FileDescriptor

const file_proto_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x15proto/scheduler.proto\x12\tscheduler\"\x9e\x01\n" +
	"\x0eTriggerRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\x129\n" +
	"\fmessage_type\x18\x04 \x01(\x0e2\x16.scheduler.MessageTypeR\vmessageType\"\x85\x01\n" +
	"\x0fTriggerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x1f\n" +
	"\vjobs_queued\x18\x04 \x01(\x05R\n" +
	"jobsQueued\"6\n" +
	"\x15ScheduleStatusRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\xa0\x02\n" +
	"\x16ScheduleStatusResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x19\n" +
	"\blast_run\x18\x03 \x01(\x03R\alastRun\x12\x19\n" +
	"\bnext_run\x18\x04 \x01(\x03R\anextRun\x12X\n" +
	"\rschedule_info\x18\x05 \x03(\v23.scheduler.ScheduleStatusResponse.ScheduleInfoEntryR\fscheduleInfo\x1a?\n" +
	"\x11ScheduleInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x96\x01\n" +
	"\vMessageType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x10\n" +
	"\fUPDATE_HOTEL\x10\x01\x12\x11\n" +
	"\rUPDATE_REVIEW\x10\x02\x12\x16\n" +
	"\x12UPDATE_TRANSLATION\x10\x03\x12\x1e\n" +
	"\x1aFETCH_MISSING_TRANSLATIONS\x10\x04\x12\x19\n" +
	"\x15FETCH_MISSING_REVIEWS\x10\x052\xb3\x01\n" +
	"\x10SchedulerService\x12E\n" +
	"\fTriggerFetch\x12\x19.scheduler.TriggerRequest\x1a\x1a.scheduler.TriggerResponse\x12X\n" +
	"\x11GetScheduleStatus\x12 .scheduler.ScheduleStatusRequest\x1a!.scheduler.ScheduleStatusResponseBPZNgithub.com/victoragudo/hotel-management-system/fetcher-service/proto/schedulerb\x06proto3"

var (
	file_proto_scheduler_proto_rawDescOnce sync.Once
	file_proto_scheduler_proto_rawDescData []byte
)

func file_proto_scheduler_proto_rawDescGZIP() []byte {
	file_proto_scheduler_proto_rawDescOnce.Do(func() {
		file_proto_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)))
	})
	return file_proto_scheduler_proto_rawDescData
}

var file_proto_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_scheduler_proto_goTypes = []any{
	(MessageType)(0),               // 0: scheduler.MessageType
	(*TriggerRequest)(nil),         // 1: scheduler.TriggerRequest
	(*TriggerResponse)(nil),        // 2: scheduler.TriggerResponse
	(*ScheduleStatusRequest)(nil),  // 3: scheduler.ScheduleStatusRequest
	(*ScheduleStatusResponse)(nil), // 4: scheduler.ScheduleStatusResponse
	nil,                            // 5: scheduler.ScheduleStatusResponse.ScheduleInfoEntry
}
var file_proto_scheduler_proto_depIdxs = []int32{
	0, // 0: scheduler.TriggerRequest.message_type:type_name -> scheduler.MessageType
	5, // 1: scheduler.ScheduleStatusResponse.schedule_info:type_name -> scheduler.ScheduleStatusResponse.ScheduleInfoEntry
	1, // 2: scheduler.SchedulerService.TriggerFetch:input_type -> scheduler.TriggerRequest
	3, // 3: scheduler.SchedulerService.GetScheduleStatus:input_type -> scheduler.ScheduleStatusRequest
	2, // 4: scheduler.SchedulerService.TriggerFetch:output_type -> scheduler.TriggerResponse
	4, // 5: scheduler.SchedulerService.GetScheduleStatus:output_type -> scheduler.ScheduleStatusResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_scheduler_proto_init() }
func file_proto_scheduler_proto_init() {
	if File_proto_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scheduler_proto_goTypes,
		DependencyIndexes: file_proto_scheduler_proto_depIdxs,
		EnumInfos:         file_proto_scheduler_proto_enumTypes,
		MessageInfos:      file_proto_scheduler_proto_msgTypes,
	}.Build()
	File_proto_scheduler_proto = out.File
	file_proto_scheduler_proto_goTypes = nil
	file_proto_scheduler_proto_depIdxs = nil
}
